DIU:
  MagicWand:
    aws:
      enabled: false
      region: 'eu-west-1'
      key: 'YOUR_AWS_ACCESS_KEY_ID'
      secret: 'YOUR_AWS_SECRET_ACCESS_KEY'
      functionName: 'hello-world'



    # the local flow command
    flowCommand: './flow'
#   # preset which is used by the clone:default command
#   defaultPreset: 'master'
    clonePresets: []
#      # the name of the preset for referencing on the clone:preset command
#      master:
#        profile: default
#
#        # the flow cli command on the remote server
#        # default is the main flowCommand-Setting
#        flowCommand: ~
#
#        # commands to execute after cloning
#        postClone:
#         - './flow help'
#
#        # informations to access the resources of the cloned setup via http
#        # if this is configured the rsync of the persistent resources is skipped
#        # and instead resources are fetched and imported on the fly once read
#        resourceProxy:
#          baseUri: http://vour.server.tld
#          persistentPath: '/_Resources/Persistent/'
#          subdivideHashPathSegment: false
#          curlOptions:
#            CURLOPT_USERPWD: very:secure

Neos:
  Flow:
    resource:

      storages:
        defaultPersistentResourcesStorage:
          storage: 'DIU\MagicWand\ResourceManagement\ProxyAwareWritableFileSystemStorage'

      targets:
        localWebDirectoryPersistentResourcesTarget:
          target: 'DIU\MagicWand\ResourceManagement\ProxyAwareFileSystemSymlinkTarget'

    mvc:
      routes:
        DIU.MagicWand:
          position: 'before Neos.Neos'
